### ISSUE TITLE
[SPIKE] Investigate private chat feature

### ISSUE THREAD

**Issue by AshciR** [rick1e/group-chat-digest#62]
It was suggested that the `/gist` offers an option to reply privately to the user. 

Suggestions:
- Check if the bot can reply privately to a user
- Come up with a name for the new command

**Comment by AshciR** [comment]
```
2024-05-23 23:34:40,163 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/ext/_application.py", line 1264, in process_update
    await coroutine
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/src/telegram_bot.py", line 103, in peek_handler
    await context.bot.send_message(chat_id=update.effective_user.id, text=private_gist)
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 2820, in send_message
    return await super().send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 1018, in send_message
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 581, in _send_message
    result = await super()._send_message(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 736, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richie/Development/python-projects/group-chat-digest/.venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 370, in _request_wrapper
    raise Forbidden(message)
telegram.error.Forbidden: Forbidden: bot can't initiate conversation with a user
```
